# Generated by Django 3.1.7 on 2021-05-12 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=11)),
                ('dob', models.DateField()),
                ('address', models.TextField(blank=True, default='')),
                ('is_driver', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250)),
                ('destination', models.CharField(max_length=250)),
                ('no_of_kms', models.IntegerField()),
                ('status', models.CharField(choices=[('draft', 'draft'), ('inprogress', 'inprogress'), ('done', 'done')], max_length=250)),
                ('Passengers', models.ManyToManyField(related_name='trip_passengers', to='bus.Passenger')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bus.passenger')),
            ],
        ),
    ]
