# Generated by Django 3.1.7 on 2021-05-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_passenger_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('fair', models.FloatField()),
            ],
        ),
    ]
